# 스프링부트 환경설정 파일(properties 또는 yml)

# 포트번호 변경
server:
  port: 8088

# 로그 레벨 및 설정
logging:
  level:
    org.springframework: DEBUG

spring:
  messages:
    basename: messages
  # 사용자가 직접 인증정보 설정하기(고정적)
  security:
    user:
      name: username
      password: passw0rd
  # JPA 설정
  jpa:
    show-sql: true

# Monitoring을 위한 Actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: "*"


